name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    strategy:
      matrix:
        include:
          - ruby: "3.3.0"
            rails: "7.1"
          - ruby: "3.3.0"
            rails: "8.0"
          - ruby: "3.3.0"
            rails: "8.1"
          - ruby: "4.0"
            rails: "8.0"
          - ruby: "4.0"
            rails: "8.1"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Appraisal
        run: bundle exec appraisal install
      - name: Tests and lint
        run: bundle exec appraisal rails-${{ matrix.rails }} bundle exec rake
