name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - "3.4"
          - "4.0"
        rails:
          - "7.1"
          - "8.0"
          - "8.1"
      fail-fast: false
    continue-on-error: ${{ matrix.ruby == '4.0' }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        continue-on-error: ${{ matrix.ruby == '4.0' }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Appraisal
        run: bundle exec appraisal install
      - name: Tests and lint
        run: bundle exec appraisal rails-${{ matrix.rails }} rake
